ALTER TABLE "ingredients" ALTER COLUMN "stock" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "ingredients" ALTER COLUMN "minimum_stock" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "bom_recipes" ALTER COLUMN "yield_quantity" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "bom_recipe_items" ALTER COLUMN "quantity" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "bom_production_runs" ALTER COLUMN "batches" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "bom_production_runs" ALTER COLUMN "produced_quantity" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "bom_production_run_items" ALTER COLUMN "consumed_quantity" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_transactions" ALTER COLUMN "quantity" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "finance_transactions" ALTER COLUMN "quantity" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_details" ALTER COLUMN "system_stock" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_details" ALTER COLUMN "cashier_actual" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_details" ALTER COLUMN "chef_actual" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_details" ALTER COLUMN "waiters_actual" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_details" ALTER COLUMN "final_actual" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_details" ALTER COLUMN "variance" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_item_summaries" ALTER COLUMN "system_stock_before" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_item_summaries" ALTER COLUMN "total_role_actual" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_item_summaries" ALTER COLUMN "final_actual" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_item_summaries" ALTER COLUMN "variance_qty" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_opname_role_inputs" ALTER COLUMN "actual_qty" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "stock_before" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "stock_after" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "stock_ledger" ALTER COLUMN "delta" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "ai_weekly_stock_projections" ALTER COLUMN "current_stock" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "ai_weekly_stock_projections" ALTER COLUMN "predicted_weekly_usage" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "ai_weekly_stock_projections" ALTER COLUMN "predicted_ending_stock" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "ai_weekly_stock_projections" ALTER COLUMN "stock_cover_days" TYPE numeric(12, 3);--> statement-breakpoint
ALTER TABLE "ai_buy_recommendations" ALTER COLUMN "recommended_quantity" TYPE numeric(12, 3);
